package com.app.sportzfever.utils;

/**
 * Created by hemanta on 12-11-2016.
 */
public class AppConstant {

    public static final String MyPREFERENCES = "MyPrefs";
    public static final String REGID = "regidKey";
    public static final String DEVICEID = "deviceidKey";
    public static final String DEVICETYPE = "android";
    public static final String TOKEN = "efc0c68e-8bb5-11e7-8cf8-008cfa5afa52";
    public static final String CATEGORYID = "category_id";
    public static final String VENDORID = "vendor_id";
    public static final String SUBCATEGORYID = "subcategory_id";
    public static final String SERVICEID = "service_id";
    public static final String CATEGORYNAME = "category_name";
    public static final String SUBCATEGORYNAME = "subcategory_name";
    public static final String CATEGORYIMAGE = "category_image";
    public static final String MALE = "1";
    public static final String BOTH = "3";
    public static final String FEMALE = "2";
    public static final String DEVICE_TYPE = "android";
    public static final String USER = "2";
    public static final String FREELANCER = "3";
    public static final String ACCEPTED = "ACCEPTED";
    public static final String ACCEPT = "ACCEPT";
    public static final String REJECT = "REJECT";
    public static final String ADDFRIEND = "ADDFRIEND";
    public static final String UNFRIEND = "UNFRIEND";
    public static final String REJECTED = "REJECTED";
    public static final String PUBLIC = "Public";
    public static final String USER_TYPE = "USER";
    public static final String CRICKET = "Cricket";
    public static final String FRIENDS = "Friends";
    public static final String ONLYME = "Only Me";
    public static final String PUSHTYPE_FRIEND = "FRIEND";
    public static final String PUSHTYPE_TEAM = "TEAM";
    public static final String TEAM = "TEAM";
    public static final String PUSHTYPE_CHAT = "CHAT";
    public static final String MATCHSTATUS_ENDED = "ENDED";

    public static final String MATCH_PAST = "MATCH_PAST";
    public static final String MATCH_LIVE = "MATCH_LIVE";
    public static final String MATCH_UP = "MATCH_UP";
    public static final String YES = "YES";
    public static final String NO = "NO";
    public static final String START = "START";
    public static final String END = "END";
    public static final String MATCHSTATUS_NOTSTARTED = "NOT STARTED";
    public static final String MATCHSTATUS_STARTED = "STARTED";
    public static final String BATSMAN = "Batsman";
    public static final String GOING = "GOING";
    public static final String BOWLER = "Bowler";
    public static final String PENDING = "PENDING";
    public static final String WICKET_KEEPER = "Wicket Keeper";
    public static final String ALL_ROUNDER = "All Rounder";
    public static final String NA = "N/A";
    public static final String RIGHTHAND = "Right Hand";
    public static final String Male = "Male";
    public static final String FeMale = "Female";
    public static final String LEFTHAND = "Left Hand";
    public static final String DEFENSIVE = "Defensive";
    public static final String AGGRESIVE = "Aggresive";
    public static final String MODERATE = "Moderate";
    public static final String FAST = "Fast";
    public static final String MEDIUM = "Medium";
    public static final String SLOW = "Slow";
    public static final String OFF_BREAK_SPIN = "Off Break spin";
    public static final String LEG_BREAK_SPIN = "Leg Break spin";
    public static final String LONG_OFF = "Long Off";
    public static final String SLIP = "Slip";
    public static final String SHORT_LEG = "Short Leg";
    public static final String MID_WICKET = "Mid Wicket";
    public static final String DEEP_MID_WICKET = "Deep Mid Wicket";
    public static final String FINE_LEG = "Fine Leg";
    public static final String SILLY_POINT = "Silly Point";
    public static final String LONG_ON = "Long On";
    public static final String MID_ON = "Mid On";
    public static final String SQUARE_LEG = "Squre Leg";
    public static final String DEEP_SQUARE_LEG = "Deep Squre Leg";
    public static final String POINT = "Point";
    public static final String DEEP_COVER = "Deep Cover";
    public static final String THIRD_MAN = "Third Man";
    public static int FRAGMENT_CODE = 201;
    public static int FRAGMENT_CODE2 = 201;
    public static int SEARCH_FRAGMENT_CODE = 202;
    public static final String MATCH = "MATCH";
    public static final String PRACTISE = "PRACTISE";
    public static final String MEET_UP = "MEET UP";
    public static final String EVENT = "EVENT";
    public static final String STATUS = "STATUS";
    public static final String BOWLED = "BOWLED";
    public static final String CATCH_OUT = "CATCH OUT";
    public static final String CAUGHT_BEHIND = "CAUGHT BEHIND";
    public static final String STUMPED = "STUMPED";
    public static final String LBW = "LBW";
    public static final String RUNOUT = "RUN OUT";
    public static final String HITWICKET = "HIT WICKET";
    public static final String BATTING = "BATTING";
    public static final String BOWLING = "BOWLING";
    public static final String RETIRED_HURT = "RETIRED HURT";
    public static final String HIT_BALL_TWICE = "HITBALL TWICE";
    public static final String HANDLED_BALL = "HANDLED BALL";
    public static final String OBSTRUCTION_TO_FIELD = "OBSTRUCTION TO FIELD";
    public static final String TIME_OUT = "TIME OUT";
    public static final String SELECT_OUT_TYPE = "Select Out Type";
    public static final String ADD_NEW_BOWLER = "Add New Bowler";
    public static String CURRENT_SELECTED_TAB = "tab_feed_bar";
    public static boolean ISFEEDNEEDTOREFRESH = false;

    public static final String UPDATENAME = "UPDATENAME";
    public static final String UPDATECAPTAIN = "UPDATECAPTAIN";
    public static final String DELETETEAM = "DELETETEAM";
    public static final int RESULTCODE_FINISH = 206;
    public static final int RESULTCODE_NEW = 210;
    public static final int RESULTCODE_FINISH1 = 207;


}
